### ISSUE TITLE
Facetted search appears to pull blank screen on mobile

### ISSUE THREAD

**Issue by little-wow** [creativecommons/open-ledger#192] opened 2017-08-07 21:17 UTC
![img_1789](https://user-images.githubusercontent.com/7093838/29046122-1277218e-7b94-11e7-8fdb-99641d859e50.PNG)
![img_1790](https://user-images.githubusercontent.com/7093838/29046123-1279346a-7b94-11e7-910a-e69824879d4e.PNG)

Regular search works fine, but facets appear to make the page blank. Using IPhone 5 + Safari. Also checked on Chrome and Safari on desktop and appears to be functioning.

**Comment by pa-w** [comment] 2017-08-15 02:26
- [ ] Try to reproduce (this seems to be a mobile only issue). Maybe CSS?
- [ ] Test locally and in staging
- [ ] Deploy!

**Comment by pa-w** [comment] 2017-08-16 23:00
So, apparently imagesloaded is the responsible and maybe it doesn't help that we use it once the DOM has loaded BUT I am going to try to wait until window.load has triggered to perform the checks. 

Here is, I think, imagesloaded bug that is causing this. Note that there is a question regarding minifying code (which we do) https://github.com/desandro/imagesloaded/issues/156

**Comment by pa-w** [comment] 2017-08-16 23:21
So, it workes! changing the event to window.load instead of DOMDocumentLoad fixed most of the issues.

Fixed in a78d747de78ec6ea1469aedd985015dec32f9c55

**Closed by pa-w** 2017-08-16 23:21 UTC
