### ISSUE TITLE
Issues with mutiple consecutive searches

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/open-ledger#203] opened 2017-10-13 19:24 UTC
Got a bug for you from info@!

===========
 
One problem that I’ve been having has been when I do multiple searches:
 
1 – Search #2 works fine
2 – Trying a search immediately after that takes me back to the original search screen.
3 – Search #3 is fine, as long as I’m on the search screen that provides the filters.  The problem seems to be if I search on the same screen that has my search results.

The person also said: "I love the beta site for creative commons search, particularly the ability to copy the attribution information so easily." which is a nice thing to hear :)

**Comment by mmoreshead** [comment] 2017-10-13 19:30
The person was using Chrome, fyi!

**Comment by pa-w** [comment] 2017-10-24 19:16
This is a duplicate of #194, will get fixed in v0.8

**Closed by pa-w** 2017-10-24 19:16 UTC
